### PR TITLE
358 - Guides Page Post Release

### LINKED ISSUE #358: [Guides] Post Release Issues
**Hub Page**
- [x] The header needs to be changed to match Abcam’s existing style. This was decided while discussing cross-sell pages. It is a change request. - **The font is incorrect for sub heading. Please change it to Noto Sans, size: 18px, line-height: 27px, letter-spacing: 0.3px** 
- [ ] On the tablet 768px and below, padding from the left and right sides should be 64px - Not fixed
- [x] On tablet portrait view, the column should be vertically stacked. Please refer to Figma - Not fixed
- [x] On mobile, there seems to be extra padding from sides in the content div - **Extra padding leading to a lot of white space**

**Guides Details Page**
- [x] For the Header, reduce the font size for h2to 56px, subtext to 18px, line height to 27px - Subtext is not as per Figma. Please use specifications mentioned for the header on hub page. Should be same across all pages.
- [x] Fix the spacing between the Chapters and Related links section to 48px - Not Fixed
- [x] Update the font styling for the link on the left-hand navigation as follows:
- [x] font-size: 16px  - Not Fixed
- [x] font-weight: 500  - Not Fixed
- [x] Padding top and bottom: 12px - Not Fixed
- [x] letter-spacing: 0.3px - Not Fixed
- [x] Please check the header for desktops on different screen sizes. For example, 1240px resolution. The same issue on the tablet 1024px - The alignment issue persists
- [ ] The browse chapter does not show up on the scroll. It has been fixed at a position - Not Fixed. Additionally, now, the 'browse' button appears below the related links section
- [x] The modal overlay for chapters is not as per design. The behaviour is also odd. The expected behaviour was explained to Amlan - not inline with the design. We can discuss over call.

- [x] Make the body text size 18px, line-height: 27px; letter-spacing 0.3px - Done but please have 24px gap.margin between paragraphs.
- [x] There is a lot of blank white space in the expanded state of the dropdown when the list is not too long. The dropdown max height should be 540px on desktop and 400px on mobile. - Please check the dropdown height. The min height of the dropdown is depended on the number of links, however if the list is too long, max-height should be 400px and then have scroller.

@shivangi1422 Please add the Guides issues you observed

### PR DESCRIPTION
**Pull request by amlan18041996**
Fix #358 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.live/en-us/technical-resources/guides/antibody-basics
- After: https://358-post-release--danaher-abcam--aemsites.hlx.live/en-us/technical-resources/guides/antibody-basics

### CODE REVIEW

**Review by sharanagoudapatil — APPROVED** [review]

File: eds/blocks/chapter-links/chapter-links.js [hunk 1]
```diff
@@ -39,8 +39,8 @@ function renderChapters(chapterItems) {
       { class: 'w-full border-b border-b-[#D8D8D8]' },
       a(
         {
-          href: item.path,
-          class: `block text-base lg:text-sm leading-6 font-semibold px-3 py-4 hover:underline ${item.path === currentPage ? 'text-black bg-[#EDF6F7]' : 'text-[#378189]'}`,
+          href: makePublicUrl(item.path),
```
Comment (pardeepgera23) [inline eds/blocks/chapter-links/chapter-links.js:42]: makePublicUrl was causing issue noticed during go-live.  ".html" extension was getting appended to chapter links due to this, so we removed call to this function. Please sync your changes with main as this function call is not required.

**Review by pardeepgera23 — APPROVED** [review]
